apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: products-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "9af7aa69-e330-46ea-b38c-af579d2718ff"
    keyvaultName: "zerotrust-kv"
    tenantId: "f3308007-477c-4a70-8889-34611817c55a"
    objects: |
      array:
        - |
          objectName: app-environment
          objectType: secret
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "2af861f7-31b0-4a63-890d-363f490efc92"
    keyvaultName: "zerotrust-kv"
    tenantId: "f3308007-477c-4a70-8889-34611817c55a"
    objects: |
      array:
        - |
          objectName: products-url
          objectType: secret
        - |
          objectName: app-environment
          objectType: secret
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: frontend-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "896b8734-c984-497c-bc28-698e6e4ede0b"
    keyvaultName: "zerotrust-kv"
    tenantId: "f3308007-477c-4a70-8889-34611817c55a"
    objects: |
      array:
        - |
          objectName: orders-url
          objectType: secret
        - |
          objectName: app-environment
          objectType: secret
