apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: products-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "ecdbd2ae-7b00-4e4a-bf01-4d278dc2b05f"
    keyvaultName: "zerotrust-kv"
    tenantId: "f3308007-477c-4a70-8889-34611817c55a"
    objects: |
      array:
        - |
          objectName: app-environment
          objectType: secret
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "3d4d37ac-483c-40ff-9f0d-3d0280c85e02"
    keyvaultName: "zerotrust-kv"
    tenantId: "f3308007-477c-4a70-8889-34611817c55a"
    objects: |
      array:
        - |
          objectName: products-url
          objectType: secret
        - |
          objectName: app-environment
          objectType: secret
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: frontend-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "c8b2f80d-60a9-45ad-b710-b82cc0ba9573"
    keyvaultName: "zerotrust-kv"
    tenantId: "f3308007-477c-4a70-8889-34611817c55a"
    objects: |
      array:
        - |
          objectName: orders-url
          objectType: secret
        - |
          objectName: app-environment
          objectType: secret
