apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "9af7aa69-e330-46ea-b38c-af579d2718ff"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "2af861f7-31b0-4a63-890d-363f490efc92"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "896b8734-c984-497c-bc28-698e6e4ede0b"
