apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "ecdbd2ae-7b00-4e4a-bf01-4d278dc2b05f"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "3d4d37ac-483c-40ff-9f0d-3d0280c85e02"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "c8b2f80d-60a9-45ad-b710-b82cc0ba9573"
